name: Deploy Backend to cPanel
on:
  push:
    branches:
      - main

jobs:
  FTP-Deploy:
    name: Fail-Safe Deployment
    runs-on: ubuntu-latest
    steps:
    - name: Get latest code
      uses: actions/checkout@v4

    - name: Sync Files to cPanel
      uses: AkaSaito/ftp-deploy@v1
      with:
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        server: ${{ secrets.FTP_SERVER }}
        # Explicit configurations to break through rigid cPanel firewalls
        port: 21
        local-dir: ./backend/
        remote-dir: /repositories/IMSolutions-Dashboard/backend/
        passive: true
